name       : zenity
version    : 3.24.0
release    : 8
source     :
    - http://ftp.acc.umu.se/pub/gnome/sources/zenity/3.24/zenity-3.24.0.tar.xz : 6ff0a026ec94e5bc1b30f78df91e54f4f82fd982f4c29b52fe5dacc886a9f7f7
homepage   : https://live.gnome.org/Zenity
license    : GPL-2.0
component  : desktop.gnome
summary    : A tool that allows you to display GTK dialog boxes in commandline and shell scripts
description: |
    A tool that allows you to display GTK dialog boxes in commandline and shell scripts.
builddeps  :
    - pkgconfig(gtk+-3.0)
    - pkgconfig(libnotify)
    - itstool
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
