name       : zenity
version    : 3.32.0
release    : 12
source     :
    - https://download.gnome.org/sources/zenity/3.32/zenity-3.32.0.tar.xz : e786e733569c97372c3ef1776e71be7e7599ebe87e11e8ad67dcc2e63a82cd95
homepage   : https://live.gnome.org/Zenity
license    : LGPL-2.0-or-later
component  : desktop.gnome
summary    : A tool that allows you to display GTK dialog boxes in commandline and
    shell scripts
description: |
    A tool that allows you to display GTK dialog boxes in commandline and shell scripts.
builddeps  :
    - pkgconfig(gtk+-3.0)
    - pkgconfig(libnotify)
    - itstool
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
