name       : zenity
version    : 3.22.0
release    : 7
source     :
    - http://ftp.acc.umu.se/pub/gnome/sources/zenity/3.22/zenity-3.22.0.tar.xz : 1ecdfa1071d383b373b8135954b3ec38d402d671dcd528e69d144aff36a0e466
homepage   : https://live.gnome.org/Zenity
license    : GPL-2.0
component  : desktop.gnome
summary    : A tool that allows you to display GTK dialog boxes in commandline and shell scripts
description: |
    A tool that allows you to display GTK dialog boxes in commandline and shell scripts.
builddeps  :
    - pkgconfig(gtk+-3.0)
    - pkgconfig(libnotify)
    - itstool
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
